---
- name: play to install apache
  hosts: devops
  become: true
  user: ansible
  tasks:
  - name: Install http package
    yum:
     name: httpd
     state: present
  - name: Download httpd.conf
    get_url:
     url: https://artifact/singam/httpd.conf.j2
     dest: /etc/httpd/conf/httpd.conf
     force: yes
  - name: create index.html
    lineinfile:
     path: /var/www/html/index.html
     line: "Hello from {{ ansible_hostname }}"
     create: yes
  - name: start and enable httpd
    service:
     name: httpd
     state: started
     enabled: true
